import test from 'node:test';
import assert from 'node:assert/strict';
import {demoProject} from '../src/ladder';
import {layoutLadder,COLUMN_WIDTH,GRID_X} from '../src/editor/layout';
import {editGridWire} from '../src/editor/grid-commands';
import {compileWithDiagnostics,compileNetwork,listNodes} from '@plc-ladder-mcp/ladder-ir';
import {snapshotSchema,snapshotHashes} from '../../../services/mcp-server/src/persistence/snapshot';
const ids=()=>{let n=0;return()=>`open-${++n}`;};
test('Down draws only one vertical stroke; Right extends an open L by exactly one cell',()=>{
 const p=structuredClone(demoProject),id=ids();
 const down=editGridWire(p,0,{row:0,column:1},'down',id);
 let root=down.project.programs[0].networks[0].root,layout=layoutLadder(root);
 assert.equal(layout.rows,2);assert.deepEqual(down.cursor,{row:1,column:1});
 const again=editGridWire(down.project,0,down.cursor,'up',id);assert.equal(layoutLadder(again.project.programs[0].networks[0].root).wires.filter(w=>w.x1===w.x2).length,0);
 const restored=editGridWire(again.project,0,again.cursor,'down',id);assert.deepEqual(restored.project,down.project);
 assert.equal(layout.wires.filter(w=>w.x1===w.x2).length,1);
 assert.equal(layout.wires.filter(w=>w.y1===w.y2 && w.y1===164).length,0);
 assert.ok(!layout.nodes.some(n=>n.y===120 && n.node.kind==='wire'));
 assert.throws(()=>compileNetwork(down.project.programs[0].networks[0]),/Open wire branch/);
 const right=editGridWire(down.project,0,down.cursor,'right',id);
 layout=layoutLadder(right.project.programs[0].networks[0].root);
 const segments=layout.nodes.filter(n=>n.y===120 && n.node.kind==='wire');
 assert.equal(segments.length,1);assert.equal(segments[0].x,GRID_X+COLUMN_WIDTH);
 assert.equal(layout.wires.filter(w=>w.x1===w.x2).length,1);
 assert.deepEqual(right.cursor,{row:1,column:2});
 const closed=editGridWire(right.project,0,right.cursor,'up',id);
 assert.equal(listNodes(closed.project.programs[0].networks[0].root).filter(l=>l.node.kind==='series'&&l.node.openEnd).length,0);
 assert.doesNotThrow(()=>compileNetwork(closed.project.programs[0].networks[0]));
 assert.deepEqual(p,demoProject);
});
test('Up and repeated Down create open rows; save round trip and compile diagnostics retain their topology',()=>{
 const id=ids();let result=editGridWire(structuredClone(demoProject),0,{row:0,column:2},'up',id);
 let layout=layoutLadder(result.project.programs[0].networks[0].root);
 assert.equal(layout.wires.filter(w=>w.x1===w.x2).length,1);assert.deepEqual(result.cursor,{row:0,column:2});
 result=editGridWire(result.project,0,result.cursor,'up',id);
 layout=layoutLadder(result.project.programs[0].networks[0].root);assert.equal(layout.rows,3);
 assert.ok(layout.wires.filter(w=>w.x1===w.x2).every(w=>w.x1===GRID_X+2*COLUMN_WIDTH));
 const parsed=snapshotSchema.parse(result.project);assert.deepEqual(parsed,result.project);
 assert.notEqual(snapshotHashes(parsed,null).logicHash,snapshotHashes(demoProject,null).logicHash);
 assert.ok(compileWithDiagnostics(parsed).diagnostics.some(d=>d.code==='OPEN_BRANCH'&&d.nodeId));
});
test('reverse vertical drawing removes only its junction; horizontal wires and symbol identities survive',()=>{
 const id=ids(),p=structuredClone(demoProject);
 const down=editGridWire(p,0,{row:0,column:1},'down',id),right=editGridWire(down.project,0,down.cursor,'right',id);
 const before=layoutLadder(right.project.programs[0].networks[0].root),leafIds=listNodes(right.project.programs[0].networks[0].root).filter(l=>l.node.kind==='wire'||l.node.kind==='contact'||l.node.kind==='action').map(l=>l.node.id);
 const removed=editGridWire(right.project,0,{row:0,column:1},'down',id),after=layoutLadder(removed.project.programs[0].networks[0].root);
 assert.equal(after.wires.filter(w=>w.x1===w.x2).length,0);assert.equal(after.rows,2);
 assert.deepEqual(after.nodes.filter(n=>n.node.kind==='wire'),before.nodes.filter(n=>n.node.kind==='wire'));
 assert.deepEqual(listNodes(removed.project.programs[0].networks[0].root).filter(l=>l.node.kind==='wire'||l.node.kind==='contact'||l.node.kind==='action').map(l=>l.node.id),leafIds);
 assert.deepEqual(snapshotSchema.parse(removed.project),removed.project);
 assert.ok(compileWithDiagnostics(removed.project).diagnostics.some(d=>d.code==='DISCONNECTED_JUNCTION'));
 const restored=editGridWire(removed.project,0,removed.cursor,'up',id);assert.deepEqual(restored.project,right.project);
 const closed=editGridWire(right.project,0,right.cursor,'up',id);
 const rightRemoved=editGridWire(closed.project,0,closed.cursor,'down',id);
 assert.equal(layoutLadder(rightRemoved.project.programs[0].networks[0].root).wires.filter(w=>w.x1===w.x2).length,1);
 assert.ok(compileWithDiagnostics(rightRemoved.project).diagnostics.some(d=>d.code==='DISCONNECTED_JUNCTION'));
 const rightRestored=editGridWire(rightRemoved.project,0,rightRemoved.cursor,'up',id);assert.doesNotThrow(()=>compileNetwork(rightRestored.project.programs[0].networks[0]));
});
test('deleting the upper left leg preserves the lower right vertical leg shown in the user images',()=>{
 const id=ids();let r=editGridWire(structuredClone(demoProject),0,{row:0,column:1},'down',id);
 r=editGridWire(r.project,0,r.cursor,'right',id);r=editGridWire(r.project,0,r.cursor,'down',id);r=editGridWire(r.project,0,r.cursor,'right',id);
 const before=layoutLadder(r.project.programs[0].networks[0].root);
 assert.equal(before.wires.filter(w=>w.x1===w.x2).length,2);
 const deleted=editGridWire(r.project,0,{row:0,column:1},'down',id),after=layoutLadder(deleted.project.programs[0].networks[0].root);
 const verticals=after.wires.filter(w=>w.x1===w.x2);assert.equal(verticals.length,1);assert.equal(verticals[0].x1,GRID_X+2*COLUMN_WIDTH);
 assert.deepEqual(after.nodes.filter(n=>n.node.kind==='wire'),before.nodes.filter(n=>n.node.kind==='wire'));assert.equal(after.rows,3);
});
