// One-time handoff of the exact previous foundation to Goose; never rewrites project data.
import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import pg from 'pg';
const schemaSignature = `
SELECT jsonb_build_object(
  'columns', (SELECT jsonb_agg(to_jsonb(c) ORDER BY c.table_name, c.ordinal_position) FROM
    (SELECT table_name, column_name, ordinal_position, data_type, udt_name, is_nullable, column_default
     FROM information_schema.columns WHERE table_schema = $1) c),
  'constraints', (SELECT jsonb_agg(to_jsonb(c) ORDER BY c.relname, c.conname) FROM
    (SELECT t.relname, k.conname, pg_get_constraintdef(k.oid) AS definition
     FROM pg_constraint k JOIN pg_class t ON t.oid = k.conrelid JOIN pg_namespace n ON n.oid = t.relnamespace WHERE n.nspname = $1) c),
  'indexes', (SELECT jsonb_agg(to_jsonb(i) ORDER BY i.tablename, i.indexname) FROM
    (SELECT tablename, indexname, indexdef FROM pg_indexes WHERE schemaname = $1) i),
  'triggers', (SELECT jsonb_agg(to_jsonb(t) ORDER BY t.relname, t.tgname) FROM
    (SELECT c.relname, g.tgname, g.tgenabled, pg_get_triggerdef(g.oid) AS definition
     FROM pg_trigger g JOIN pg_class c ON c.oid = g.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = $1 AND NOT g.tgisinternal) t),
  'functions', (SELECT jsonb_agg(pg_get_functiondef(p.oid) ORDER BY p.proname)
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = $1)
) AS signature`;
export async function adoptKysely(client) {
  await client.query('BEGIN');
  try {
    const history = await client.query("SELECT name FROM public.kysely_migration ORDER BY name");
    if (history.rows.length !== 1 || history.rows[0].name !== '001-project-revisions') throw new Error('Only the exact previous foundation can be adopted.');
    const tracked = await client.query("SELECT to_regclass('public.goose_db_version')::text AS present");
    if (tracked.rows[0].present) throw new Error('Goose history already exists; use goose status/up.');
    await client.query('LOCK TABLE app.projects, app.project_revisions, app.project_save_requests IN ACCESS EXCLUSIVE MODE');
    const compare = 'app_goose_adoption_check';
    const source = await readFile(new URL('../db/migrations/00001_project_revisions.sql', import.meta.url), 'utf8');
    const baseline = source.split('-- +goose Down')[0].replace(/^--.*$/gm, '').replace(/\bapp\./g, compare + '.').replace('CREATE SCHEMA app;', `CREATE SCHEMA ${compare};`);
    await (client.exec ? client.exec(baseline) : client.query(baseline));
    const actual = JSON.stringify((await client.query(schemaSignature, ['app'])).rows[0].signature);
    const expected = JSON.stringify((await client.query(schemaSignature, [compare])).rows[0].signature).replaceAll(compare, 'app');
    if (actual !== expected) throw new Error('Existing schema differs from the exact foundation; adoption refused without changing data.');
    // Remove the comparison schema explicitly, without CASCADE.
    const down = source.split('-- +goose Down')[1].replace(/^--.*$/gm, '').replace(/\bapp\./g, compare + '.').replace('DROP SCHEMA app;', `DROP SCHEMA ${compare};`);
    await (client.exec ? client.exec(down) : client.query(down));
    await client.query(`CREATE TABLE public.goose_db_version (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      version_id bigint NOT NULL, is_applied boolean NOT NULL, tstamp timestamp NOT NULL DEFAULT now()
    )`);
    await client.query('INSERT INTO public.goose_db_version (version_id, is_applied) VALUES (0, true), (1, true)');
    // Legacy tracking is retained as provenance; it must never be used as a second migrator.
    await client.query('COMMIT');
  } catch (error) { await client.query('ROLLBACK'); throw error; }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const connectionString = process.env.DATABASE_URL ?? process.env.GOOSE_DBSTRING;
  if (!connectionString) { console.error('Set DATABASE_URL for the existing local foundation database.'); process.exit(1); }
  const client = new pg.Client({ connectionString });
  try { await client.connect(); await adoptKysely(client); console.log('Foundation adopted at Goose version 1. Run npm run db:migrate:up.'); }
  catch { console.error('Adoption failed; no changes committed. Expected the unchanged Kysely foundation and no Goose history. Stop the application and inspect the schema before retrying.'); process.exitCode = 1; }
  finally { await client.end(); }
}
